// LUCIDE — catalogue produits · « Voir clair. »
// Chaque produit porte son PRIX-VÉRITÉ : décomposition honnête du coût.
// verite = {matiere, verres, facon, transport, marge}  (somme = price, en €)
window.LUCIDE_CATALOG = [
  // ───────────────────────── LE VERRE NU (lunettes de vue) ─────────────────────────
  {slug:"v01-aube", name:"L'Aube", line:"Le Verre Nu", price:95, badge:"Iconique",
   tagline:"Acétate translucide, lumière de 6 h du matin",
   desc:"La monture qui a lancé la maison. Acétate italien translucide rosé, charnières vissées, verres organiques anti-reflet inclus. Le premier regard du jour, en clair.",
   specs:["Acétate bloc Mazzucchelli (Italie)","Verres organiques 1.5 anti-reflet inclus","Charnières vissées, réparable à vie","Largeur 140 mm · pont 19 mm"],
   verite:{matiere:14,verres:21,facon:18,transport:3,marge:39}},
  {slug:"v02-meridien", name:"Le Méridien", line:"Le Verre Nu", price:110, badge:null,
   tagline:"Métal fin, rondes, sans esbroufe",
   desc:"Titane brossé, rondes, 11 g sur le nez. Pour celles et ceux qui veulent disparaître derrière leur regard. Plaquettes ajustables, zéro vis apparente.",
   specs:["Titane bêta recyclé","Verres organiques 1.5 anti-reflet inclus","11 g · hypoallergénique","Pont 21 mm"],
   verite:{matiere:21,verres:21,facon:20,transport:3,marge:45}},
  {slug:"v03-comptoir", name:"Le Comptoir", line:"Le Verre Nu", price:98, badge:null,
   tagline:"Écaille honnête, panto intemporel",
   desc:"La forme panto, l'écaille d'acétate vrai (pas d'imprimé), montée à la main. Celle qu'on porte vingt ans et qu'on transmet.",
   specs:["Acétate écaille véritable","Verres organiques 1.5 inclus","Monté main, atelier du Jura","Largeur 142 mm"],
   verite:{matiere:15,verres:21,facon:19,transport:3,marge:40}},
  {slug:"v04-demi-lune", name:"La Demi-Lune", line:"Le Verre Nu", price:75, badge:"Lecture",
   tagline:"La loupe dosée à ta vraie vue",
   desc:"Demi-lune de lecture, correction +1 à +3 dosée chez l'opticien — pas une loupe de supermarché. Léger, à glisser dans la poche de chemise.",
   specs:["Acétate noir mat / miel","Correction dosée +1.0 à +3.0","Étui plat inclus","8 g"],
   verite:{matiere:9,verres:18,facon:14,transport:2,marge:32}},
  {slug:"v05-ecran", name:"L'Écran", line:"Le Verre Nu", price:89, badge:"Le seul traitement utile",
   tagline:"Filtre lumière bleue — et rien d'autre",
   desc:"Le seul « traitement » qu'on assume : un vrai filtre lumière bleue pour les journées d'écran. Pas de promesse magique, une mesure. Monture mixte légère.",
   specs:["Filtre lumière bleue mesuré (−40 % à 450 nm)","Acétate cristal","Verres sans correction ou dosés","Test de filtration fourni"],
   verite:{matiere:12,verres:24,facon:15,transport:3,marge:35}},

  // ───────────────────────── PLEIN JOUR (solaires) ─────────────────────────
  {slug:"s01-plein-sud", name:"Plein Sud", line:"Plein Jour", price:125, badge:"Iconique",
   tagline:"Masque d'aube, UV réels mesurés",
   desc:"Le masque solaire de la maison. Teinte dégradée couleur d'aube, catégorie 3, UV400 vérifié et certificat dans la boîte. On bronze le regard, on ne joue pas avec.",
   specs:["Verres CR-39 cat. 3 · UV400 certifié","Teinte dégradée 'aube'","Acétate translucide miel","Certificat de filtration UV joint"],
   verite:{matiere:16,verres:26,facon:21,transport:4,marge:58}},
  {slug:"s02-lucide-noir", name:"Lucide Noir", line:"Plein Jour", price:115, badge:null,
   tagline:"Le wayfarer net, sans logo géant",
   desc:"Noir profond, ligne franche, aucune signature voyante — juste l'emblème gravé à l'intérieur. La paire qu'on ne perd pas parce qu'on ne s'en sépare pas.",
   specs:["Acétate noir bloc","Verres minéraux cat. 3 · UV400","Charnières vissées","Largeur 145 mm"],
   verite:{matiere:15,verres:24,facon:20,transport:4,marge:52}},
  {slug:"s03-mirage", name:"Mirage", line:"Plein Jour", price:135, badge:"Édition lumière",
   tagline:"Verres miroir couleur de rosée",
   desc:"Miroir rose-doré à l'extérieur, vision neutre à l'intérieur. La lumière d'aube, portée. Catégorie 3, traitement miroir résistant.",
   specs:["Verres miroir flash 'rosée' cat. 3","UV400 certifié","Titane + acétate","Étui rigide inclus"],
   verite:{matiere:18,verres:30,facon:22,transport:4,marge:61}},
  {slug:"s04-pilote-vrai", name:"Le Pilote Vrai", line:"Plein Jour", price:140, badge:null,
   tagline:"L'aviateur honnête",
   desc:"La goutte aviateur en titane, verres polarisants vrais (test inclus). Pour regarder l'horizon sans plisser les yeux ni le portefeuille.",
   specs:["Verres polarisants cat. 3 (test fourni)","Titane doré champagne","Plaquettes ajustables","UV400 certifié"],
   verite:{matiere:20,verres:31,facon:22,transport:4,marge:63}},

  // ───────────────────────── L'ATELIER (objets & transparence) ─────────────────────────
  {slug:"a01-boite-noire", name:"L'Étui Boîte Noire", line:"L'Atelier", price:29, badge:"Signature",
   tagline:"Le prix-vérité gravé au laser",
   desc:"Étui rigide en aluminium recyclé. À l'intérieur du couvercle : la décomposition du coût de TA paire, gravée. L'objet le plus honnête de ta poche.",
   specs:["Aluminium recyclé","Gravure prix-vérité personnalisée","Mousse intérieure recyclée","Fermeture aimantée"],
   verite:{matiere:9,verres:0,facon:7,transport:2,marge:11}},
  {slug:"a02-chamoisine", name:"La Microfibre Honnête", line:"L'Atelier", price:9, badge:null,
   tagline:"Ça nettoie. C'est tout. C'est déjà bien.",
   desc:"Microfibre tissée en France, imprimée de la Charte LUCIDE en six lignes. On ne lui demande pas de faire du marketing, juste de nettoyer.",
   specs:["Microfibre tissée en France","Charte LUCIDE imprimée","Lavable 200 fois","18 × 18 cm"],
   verite:{matiere:2,verres:0,facon:2,transport:1,marge:4}},
  {slug:"a03-lien", name:"Le Lien", line:"L'Atelier", price:19, badge:null,
   tagline:"Cordon-chaîne, pour ne plus les chercher",
   desc:"Cordon en coton ciré et maillons d'acier recyclé. Se porte été comme hiver. Parce qu'une lunette qu'on retrouve, c'est une lunette qu'on garde à vie.",
   specs:["Coton ciré + acier recyclé","Embouts silicone universels","70 cm ajustable","Teintes aube / encre / verre"],
   verite:{matiere:6,verres:0,facon:4,transport:1,marge:8}},
  {slug:"a04-ordonnance", name:"Le Kit Ordonnance", line:"L'Atelier", price:24, badge:null,
   tagline:"L'entretien dosé comme une prescription",
   desc:"Spray nettoyant rechargeable, tournevis d'horloger, plaquettes de rechange, chiffon. Tout ce qu'il faut pour faire durer, rien de superflu. Recharges en pharmacie d'optique.",
   specs:["Spray rechargeable 30 ml","Tournevis + vis de rechange","Plaquettes nez de rechange","Recharges disponibles"],
   verite:{matiere:8,verres:0,facon:6,transport:2,marge:8}},
  {slug:"a05-ardoise", name:"L'Ardoise Prix-Vérité", line:"L'Atelier", price:39, badge:"Manifeste",
   tagline:"L'objet-manifeste : nos marges, en grand, chez toi",
   desc:"Une ardoise émaillée façon plaque de pharmacie, où l'on a gravé la décomposition moyenne du prix d'une lunette LUCIDE — et celle de l'industrie, à côté. À accrocher au mur comme un acte de foi. La pièce la plus partagée de la maison.",
   specs:["Acier émaillé, façon plaque d'apothicaire","30 × 40 cm","Édition numérotée","Crochets fournis"],
   verite:{matiere:11,verres:0,facon:9,transport:3,marge:16}},
];
